language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=x86_64
android:
  components:
  - platform-tools
  - tools

  - build-tools-23.0.3
  - android-23
  - extra
  - addon
  #- sys-img-x86_64-android-23
before_script:
  # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- adb wait-for-device
  #- adb shell input keyevent 82 &
script:
  - ./gradlew check
deploy:
  provider: releases
  api_key:
    secure: F16MI47/lpnwEd8kBxrwhmHuXw3sVLaeASfxASg5pVjvdX7mITaX6Zqta1skdyGG0Nzi9QVingrNKHDueLq/wd1EODKNCayOcxO56bH6gQEznhQ/TueXclJpQgZX10FtvG3leR5vPfJMNmjEj3AwmyYdQQ3X7o1RmPWSIERgP2WAzn27ZPX5a9agOhG+rheAC0AZkjTXx0L/++1+QEiQaYarOcrwVdp1E5zduU81Nc5tnbUP8HWfV9AWIWayYQ/DBqS46cDIDVSyeq/mHhlnl/ZVpee4I9dTOzmLyM77V603oh24wc4RtClNL/k5M0rpGBp6CRBBeJeiBW1Vaf1UaZc6cpAbVUp3LNoBBPvGVjvGWqi0ZkHjWvGhkdoCQMT7TxiF6+j1zkrjSv7fa0hqkADuaLsoBc1TdXPNqJR2IhNAxeaAen3h3z+rqwenKs/ebTkmotYHfVNpnH5aL+7aGM+oxOOV6MB2mPbw2UKtGHbwt4Iw9z7BmNWhyu3Y7NtS6i8YJ3wfOJjRQ6JAVKdbaWWF6UTJLJzyF6947FbeXlm/b9PA3PRwclFVUyuPPCfQNKvXkNpDE0aOuyoHqpFJ+yrE4Swz4mSIoBUAliPWEj21yb5yexuOOel4YVibLm/iqpcZlLwzvhdgwFEgCjLtVoTQbSftBFwIKLkzHTWHX+Q=
  file_glob: true
  file: "*/build/libs/*.jar,*/build/outputs/aar/*-release.aar"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- "./gradlew stetho:bintrayUpload stetho-no-op:bintrayUpload stetho-okhttp:bintrayUpload stetho-okhttp-no-op:bintrayUpload stetho-timber:bintrayUpload stetho-timber-no-op:bintrayUpload"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/"
